### ISSUE TITLE
[회의] 프로젝트 주제 확정

### ISSUE THREAD

**Issue by mina-dong** [LovellR/GSS_Project#1]
< 오픈소스 기초 프로젝트 주제 확정>

저번 회의를 토대로, 프로젝트 주제 확정하고자 합니다. 
이번 프로젝트 주제가 건강과 관련있어야하는데,
 "약"과 관련된 주제는 어떤가요?

차별성과 같이 언급하면 좋을 듯합니다.

@san-sae @LovellR

**Comment by san-sae** [comment]
주제 : 약물 오용
개인의 특성(ex. 나이, 기저질환 등)에 따라 복용하지 말아야 하는 약물을 알려주는 프로그램 어떨까요?
