### ISSUE TITLE
의약품정보 공공데이터/공개데이터

### ISSUE THREAD

**Issue by LovellR** [LovellR/GSS_Project#18]
현재 프로젝트를 위해 수집한 데이터가 노인주의약물, 병용금기약물, 연령별금기의약품, 임산부금기의약품으로 총 4개입니다.

DB에서 PK, FK 지정을 위해 메인이 되는 의약품 성분 및 의약품 정보 데이터가 필요합니다.

[https://www.data.go.kr/data/15095677/openapi.do#tab_layer_detail_function](url)

위의 링크와 연결된 공공데이터가 가장 적합하지만 성분명이 한글로 작성되어 있어서 FK로 지정이 불가합니다.
관련된 적합한 데이터를 찾아야 될거 같습니다.

**Comment by mina-dong** [comment]
이미 저번에 카톡으로 대화를 나누긴 했지만
저도 그 이후에 더 찾아봤는데
약학정보원에서 약에대한 기본정보는 여기에 있는거 같더라고요
근데 나머지 글 찾아보니 해당 api는 유료인듯 싶습니다.

기본정보를 표시하는 건 포기하고,
기존에 수집했던 정보를 가지고 표현해야할거 같습니다.

**Comment by san-sae** [comment]
노인주의, 임부주의 데이터는 csv 파일을 가져와 사용하였습니다.
