### ISSUE TITLE
네비게이션 바 레이아웃

### ISSUE THREAD

**Issue by mina-dong** [LovellR/GSS_Project#36]
![image](https://github.com/LovellR/GSS_Project/assets/82349462/3c2ef5c8-f6ee-434d-ac3f-fe2683f3c1b9)

전체 화면일 땐 괜찮은데 화면 크기를 줄이거나 하면 한쪽으로 쏠리는 형태가 됩니다
margin이나 이런 설정을 이것저것 해봤는데도 잘 안되네요
이 현상 해결하실 수 있으시면 도움 부탁드립니다

**Comment by LovellR** [comment]
html 형식 white-space가 기본적으로 전체 표기가 안되면 줄바꿈 하게 되있어서 css에서 안되게 하면 아마 해결될겁니다.

**Comment by LovellR** [comment]
반응형으로 대상 화면 크기 받아와서 글씨 크기를 줄이게 설정해도 해결은 됩니다.

**Comment by mina-dong** [comment]
> html 형식 white-space가 기본적으로 전체 표기가 안되면 줄바꿈 하게 되있어서 css에서 안되게 하면 아마 해결될겁니다.

반응형까진 구현안하고 이 방법으로 해당건 처리했습니다
