### ISSUE TITLE
MySQL Error Code: 1064. You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by mina-dong** [LovellR/GSS_Project#40]
![image](https://github.com/LovellR/GSS_Project/assets/82349462/6a5e792f-b7ad-4872-bed3-10297122e3bb)

use database 맞지 않나요 자꾸 문법이 틀렸다고 나와요...

**Comment by LovellR** [comment]
세미콜론 붙여야합니다

**Comment by mina-dong** [comment]
감사합니다!


> 세미콜론 붙여야합니다

**Comment by mina-dong** [comment]
SQL 수정 해서 조회했고, 해당 부분 커밋하였습니다.
