### ISSUE TITLE
약국정보 페이지 - Pharmacy.js

### ISSUE THREAD

**Issue by mina-dong** [LovellR/GSS_Project#41]
관련 이슈: #37

- [x] 공개 api에서 데이터 가져오기
- [x] pharmacy.js 만들기
- [x] server 통해서 데이터 보내기
- [x] 지역별로 쿼리 만들어서 적용하기

**Comment by mina-dong** [comment]
가지고 있는 데이터가 위도, 경도 까지 가져오는 건데 우선 리스트 형태로 이름이랑 주소까지만 가져왔습니다

**Comment by mina-dong** [comment]
![image](https://github.com/LovellR/GSS_Project/assets/82349462/baffc30c-f4d9-4ed9-ab38-e879da4836b5)

**Comment by san-sae** [comment]
![image](https://github.com/LovellR/GSS_Project/assets/97453758/8023d1e3-a71c-4640-99d6-82c4753848a7)

제가 실행시켰을 때는 도시를 청주시로 선택했을 때 아무 것도 띄지 않네요
다시 확인 부탁 드립니다.

**Comment by mina-dong** [comment]
@san-sae 
my-sql 깔고 제가 올린 db 연결하셨나요?
