### ISSUE TITLE
AI 학습데이터

### ISSUE THREAD

**Issue by LovellR** [LovellR/GSS_Project#43]
경구약제조합이 총 용량이 적어서 진행하려했는데 약물조합당 3장 뿐이라 정확도가 낮을거 같아서 단일경구약제 중 하나로 진행해야 할 것 같습니다.

단일경구약제 파일이 약 90기가 80종이기에 그중에 선별해야 될 것 같습니다.

**Comment by mina-dong** [comment]
네 알겠습니다

**Comment by LovellR** [comment]
병용금지 약물 있는 10번 파일 사용
