### ISSUE TITLE
CSS 코드 구현시 주의사항

### ISSUE THREAD

**Issue by san-sae** [LovellR/GSS_Project#47]
![image](https://github.com/LovellR/GSS_Project/assets/97453758/7aa61c75-a02e-468d-b064-09a5bd9ad707)

제가 본래 의도했던 스타일링은 테이블의 헤더부분이 파란색이 아니였는데
민아님이 다른 컴포넌트에 해당하는 CSS코드를 구현하시다가 User.js에 영향을 미쳤습니다.

앞으로 CSS코드를 구현하실 때 단순히 태그만 사용하지 마시고 class나 id를 활용해주시기 바랍니다.

예시.
table { border: 1px solid red }; (x)
.hello_table { border: 1px solid red }; (o)

**Comment by mina-dong** [comment]
알아서 수정 부탁드릴게요 저도 유림님이 쓰신 css  몇몇개 그냥 영향받았는데 제가 알아서 클래스 또는 아이디 추가해서 썼습니다

**Comment by san-sae** [comment]
넵 감사합니다

저도 뒤늦게 깨달은 거라 앞으로 태그 이용하는 건 자제해야 할 것 같아요
