### ISSUE TITLE
서버 구동 문제

### ISSUE THREAD

**Issue by san-sae** [LovellR/GSS_Project#67]
프로젝트 디렉토리/src/server 위치에서
node server.js 명령어를 입력했는데 서버가 구동이 되지 않습니다.
해결방법을 아시는 분은 코멘트 달아주시길 바랍니다.

**Comment by mina-dong** [comment]
0. 에러코드 확인 
1. 모듈 설치여부 확인
2. 컴퓨터 재부팅
서버구동시 log에 아마 root 가 나올거예요! 그리고 database to ~ 라면서 연결되면 log 나오게 했습니다.
