### ISSUE TITLE
구현해야 할 페이지 

### ISSUE THREAD

**Issue by san-sae** [LovellR/GSS_Project#7]
병용금기 약물 정보 제공 웹에서 필요한 페이지에 대한 논의를 하려고 합니다.

페이지 종류
1. 웹 시작 페이지
2. 개인정보 입력 페이지(해당 페이지는 이미 구현된 페이지입니다.)
3. 약품 입력 페이지
4. 약품 결과 출력 페이지

이 외에도 구현되어야 할 페이지가 있으시면 코멘트 달아주시길 바랍니다.

**Comment by mina-dong** [comment]
![image](https://github.com/LovellR/GSS_Project/assets/82349462/3ee3c6cb-1435-4f3c-8557-e2c6ca359cd2)
![image](https://github.com/LovellR/GSS_Project/assets/82349462/135583ad-1118-4e1a-addd-014ea6173188)
![image](https://github.com/LovellR/GSS_Project/assets/82349462/97e10d45-85e4-45a5-9ebb-7513b95faa46)
![image](https://github.com/LovellR/GSS_Project/assets/82349462/811e682b-96e9-4899-8f99-ec87afb81d01)

detail -> 개인정보기준서치 @san-sae 
home @san-sae 
menu @mina-dong 
search -> @mina-dong 병용금지서치
user => @san-sae home안에 불러오는 형태일것. 개인정보입력.
* 문의 미정
