### ISSUE TITLE
AI 사용 가능한 종류 제한

### ISSUE THREAD

**Issue by LovellR** [LovellR/GSS_Project#71]
대우세파클러캡슐 250mg
드로세프캡슐 500mg
삼아아토크정 20mcg
프라스탄정 5mg
토비콤에스연질캡슐 100mg/PTP
무테린캡슐 200mg
화니돌0.5마이크로그램연질캡슐
트라시논정 1mg
산디문뉴오랄연질캡슐 25mg
에이프로젠나프록센나트륨정 275mg/PTP
비유피-4정 10mg
비유피-4정 20mg
베이슨정 0.2mg
이바펜400mg정
바이메틴정 100mg/PTP (수출용)

위의 종류로 ai인식은 제한됩니다.

**Comment by mina-dong** [comment]
네 확인했습니다.
